services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=booking_password
      - POSTGRES_DB=booking_db_v2
    ports:
      - '5432:5432'