spring:
  application:
    name: Booking Service API
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db_v2
    username: postgres
    password: booking_password
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/db.changelog.yaml