INSERT INTO public.unit (number_of_rooms, unit_type, floor, base_price, total_price) VALUES(5, 'APARTMENT', 25, 1500, 1725);
INSERT INTO public.unit (number_of_rooms, unit_type, floor, base_price, total_price) VALUES(4, 'APARTMENT', 25, 1000, 1150);
INSERT INTO public.unit (number_of_rooms, unit_type, floor, base_price, total_price) VALUES(6, 'APARTMENT', 25, 2000, 2300);
INSERT INTO public.unit (number_of_rooms, unit_type, floor, base_price, total_price) VALUES(6, 'APARTMENT', 25, 1200, 1380);
INSERT INTO public.unit (number_of_rooms, unit_type, floor, base_price, total_price) VALUES(2, 'FLAT', 5, 400, 460);
INSERT INTO public.unit (number_of_rooms, unit_type, floor, base_price, total_price) VALUES(1, 'FLAT', 4, 300, 345);
INSERT INTO public.unit (number_of_rooms, unit_type, floor, base_price, total_price) VALUES(3, 'FLAT', 3, 700, 805);
INSERT INTO public.unit (number_of_rooms, unit_type, floor, base_price, total_price) VALUES(2, 'FLAT', 2, 600, 690);
INSERT INTO public.unit (number_of_rooms, unit_type, base_price, total_price) VALUES(4, 'HOME', 700, 805);
INSERT INTO public.unit (number_of_rooms, unit_type, base_price, total_price) VALUES(2, 'HOME', 450, 517.5);
INSERT INTO public.unit (number_of_rooms, unit_type, base_price, total_price) VALUES(2, 'HOME', 350, 402.5);
INSERT INTO public.unit (number_of_rooms, unit_type, base_price, total_price) VALUES(4, 'HOME', 1300, 1495);